### ISSUE TITLE
Trojan detected: Trojan.Presenoker ?

### ISSUE THREAD

**Issue by alx-xlx** [bitbrute/evillimiter-windows#7]
Should I be worried ?

![cn845MJDWD](https://user-images.githubusercontent.com/42188371/70269829-25e74400-17c9-11ea-892a-7712ed356788.png)

**Comment by Korayem** [comment]
Hmmm https://www.virustotal.com/gui/file/51049aa8ae9be6e8e895e16c48a040ce2fac05feb4543b29cbd87ddacbb3f5e9/detection

![image](https://user-images.githubusercontent.com/198332/70869021-3a78c880-1f8f-11ea-88e4-f608e5900d70.png)

**Comment by bitbrute** [comment]
Well, this software employs a lot of techniques that are quite shady in order to get the desired result. As correctly pointed out by lots of the anti-virus softwares: this tool makes use of a library called [WinDivert](https://www.reqrypt.org/windivert.html) that injects itself into the Windows kernel and does some funny things with the network packet management, which is required to slow the connection of the devices down.
